services:
  finbert:
    command: ["uv", "run", "python3", "/src/main.py"]
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8080:8080
    volumes:
      - ./finbert:/src/finbert
      - ./models:/src/models
      - ./notebooks:/src/notebooks
      - ./scripts:/src/scripts
      - ./main.py:/src/main.py
      - ./keys.json:/src/keys.json